### ISSUE TITLE
dosen't use say method

### ISSUE THREAD

**Issue by cmtheta** [ramune8862/practice01#6]
testest

**Comment by ramune8862** [comment]
warawara

**Comment by ramune8862** [comment]
resolve
[](https://github.com/ramune8862/practice01/commit/a4e45ffb01779865fcf784ff2102197cd7bff58d)

**Comment by ramune8862** [comment]
[1](https://github.com/ramune8862/practice01/commit/a4e45ffb01779865fcf784ff2102197cd7bff58d)

**Comment by ramune8862** [comment]
[javavava]()
[request](https://github.com/ramune8862/practice01/pull/7)

**Comment by cmtheta** [comment]
aaa
